### PR TITLE
Redesigned readme

### PR DESCRIPTION
**Pull request by aguilaair**
Heavily inspired by: https://github.com/marktext/marktext (thanks :))

### CODE REVIEW

**Comment by aguilaair** [comment]
@leoafarias do you like it?

**Comment by aguilaair** [comment]
https://github.com/leoafarias/sidekick/tree/readme-update#readme

**Comment by leoafarias** [comment]
> @leoafarias do you like it?

Looks great!

**Review by leoafarias — APPROVED** [review]
LGTM

**Comment by aguilaair** [comment]
Great! let's merge #173 first just so the logo isn't pointing to a branch which is gonna get deleted

**Pull request merged**
