### PR TITLE
Fix #100 (Change DB location)

### LINKED ISSUE #100: App doesn't work in macOS without access permission to Documents
### issue:
The app doesn't work if access permission to Documents were not allowed in macOS. 

### To reproduce:

- close the app. 
- remove access permission from SideKick:
Screen Shot 2021-06-20 at 12 31 52 AM

- open the app again
- The app would look like:

Screen Shot 2021-06-20 at 12 29 20 AM

### Additional info:
- System: macOS Big Sur 11.2.3 (20D91)
- SideKick: 0.1.1

---
btw, In an older version, I got this screen and saved it but I forgot to file an issue at the time. 
Screen Shot 2021-06-11 at 4 24 23 PM

### PR DESCRIPTION
**Pull request by aguilaair**
This would be a breaking change as all user settings (for sidekick) would be lost. This PR simply changes the db location to the `getApplicationSupportDirectory()` instead of the Documents folder, which should solve permission issues.

Linked PR: https://github.com/flutter/plugins/pull/3691

### CODE REVIEW

**Comment by leoafarias** [comment]
Want to do some research how difficult is to copy the data from the old directory to the new one through hive before merging.

**Comment by aguilaair** [comment]
Shouldn't be too bad: 

```
  if (oldHiveDB.exists()) {
    File(oldHiveDB.path).copy(newPath);
    File(oldHiveDB.path).delete();
  }
```
(pseudocode, but bascially this)

**Comment by leoafarias** [comment]
> Shouldn't be too bad:
> 
> ```
>   if (oldHiveDB.exists()) {
>     File(oldHiveDB.path).copy(newPath);
>     File(oldHiveDB.path).delete();
>   }
> ```
> 
> (pseudocode, but bascially this)

Do you want to give it  a go so we can merge?

**Comment by aguilaair** [comment]
@leoafarias done, tested it on windows and Linux, would appreciate if you could double check on MacOS too

**Comment by aguilaair** [comment]
Ideally, this should be removed in (for example) 6 months, as this r/w operation slows down the start of the app (not by much, but still). It also can't be moved any later because the app depends on reading the DB, which becomes locked after it is initialized and therefore data integrity cannot be guaranteed nor can the old DB be deleted.

**Comment by leoafarias** [comment]
I still have to test this, but just added a check on preferences for the migration, so we are not always running

**Comment by aguilaair** [comment]
Sounds good

**Comment by leoafarias** [comment]
@aguilaair do we have to tackle #104 as part of this?

**Comment by aguilaair** [comment]
IMO it is a separate issue

**Comment by leoafarias** [comment]
@aguilaair can you confirm the issue is fixed on windows and Linux? On Mac it’s working

**Comment by aguilaair** [comment]
Yep

**Pull request merged**
