### PR TITLE
feature/internationalization

### PR DESCRIPTION
**Pull request by Ahmadre**
## Motivation

After discussing the internationalization topic with the Collaborators & Maintainers, I wanted to simplify and reimagine this part in the app.

Benefits are:
- Decouple translations from different team members (developers can focus on the actual logic and everyone who isn't a developer can contribute the texts with less knowledge). Non-developers just have to add an entry to `_supportedLanguagesCodes` in `LanguageManager` and the corresponding folder-strcuture.
- Namespacing, structuring, organizing every part of translation is possible through https://pub.dev/packages/i18next
- Supports now web resolutions for locals (through `localeResolutionCallback`)
- Some parts of the existing code will be refactored.

## Issues

Closes: https://github.com/leoafarias/sidekick/issues/81

### CODE REVIEW

**Comment by Ahmadre** [comment]
@leoafarias 

In `lib/src/modules/updater/components/update_info.dart` is a TextButton with an empty function signature. Is that intended?

Bildschirmfoto 2021-08-08 um 22 36 30

**Comment by Ahmadre** [comment]
@leoafarias & others: I've finished the migration and fixed some typos & translations.

**Comment by Ahmadre** [comment]
I've added Spanish, that one can also see what I did to add a new translation.

**Comment by leoafarias** [comment]
@Ahmadre Thank you for your work on this, I will go ahead and review your comments.

**Comment by Ahmadre** [comment]
I recognized a little bug by resetting to default settings. I'll fix this and then it should be ready from my side

**Comment by Ahmadre** [comment]
Fixed

**Comment by leoafarias** [comment]
@all-contributors please add @Ahmadre  for code, doc, translation

**Pull request merged**
