### PR TITLE
Make playground text selectable

### LINKED ISSUE #155: [Feature Request] Allow selection (and copying) of text in playground console output
It would be handy to be able to copy & paste errors shown in the console.

### PR DESCRIPTION
**Pull request by aguilaair**
Closes #155

### CODE REVIEW

**Comment by aguilaair** [comment]
Not completely happy yet as it is a single-line selection and this means that the behavior is not completely expected:
image

**Comment by leoafarias** [comment]
@aguilaair is this ready for review? You mentioned that you are not completely happy with the behavior

**Comment by aguilaair** [comment]
If  the above is acceptable, then yes, @leoafarias

**Comment by leoafarias** [comment]
@aguilaair changed to a rich text element, and now it works well with a multi select

**Pull request merged**
