### PR TITLE
Fix/I18Next Windows Paths and null errors

### PR DESCRIPTION
**Pull request by Ahmadre**
@aguilaair Here's a branch with a different key for hive to save the locale and a little fix for isCached null error.

Could you please checkout my branch and try it out on your PC?

After that just comment here if it is fixed on your side.

Best regards

### CODE REVIEW

**Comment by aguilaair** [comment]
Hey! It's a littñe late here in Spain, but i will check it out first thing in the morning.

Thanks!

**Comment by aguilaair** [comment]
This has not fixed the issue on my PC. I've also tried deleteing all settings files to ensure there was no collision, but that didn't work either.

**Comment by Ahmadre** [comment]
> This has not fixed the issue on my PC. I've also tried deleteing all settings files to ensure there was no collision, but that didn't work either.

That's weird :( on my machine it works without any problems. I'll make a video or screenshots

**Comment by Ahmadre** [comment]
Maybe you have some time so I can have a look at it with TeamViewer or other tools

**Comment by Ahmadre** [comment]
By the way: this has nothing to do with intl! I18Next is working out of the box! It looks like that your app can't find or load the translation strings!

**Comment by Ahmadre** [comment]
@aguilaair I contacted you via twitter and email. Maybe you can check your mails.

I also checked out the main branch in sidekick and just started the app and it's working perfectly.

Here's a video demo of the test (Remember you tried out the PR and not the merged one). Could you please checkout the main branch?:

https://user-images.githubusercontent.com/18512224/129451037-ed6d3ccc-5903-4cf0-b3ea-5a410eed7880.mov

**Comment by Ahmadre** [comment]
Thank you for the meeting @aguilaair :) 

For all other:
- macOS
- Linux are working

The problem only exists in Windows and there're no errors.

I'll investigate into this and let you know when I tested it on my Parallels on mac.

**Comment by Ahmadre** [comment]
Related Issue: https://github.com/nubank/i18next/issues/36

**Comment by Ahmadre** [comment]
@aguilaair @leoafarias I fixed it 😅 

I18Next handled the path wrong. It tried to generate the Windows path style with the path package. But you shouldn't do that for Flutter on every platform. Only if you work with files in the OS.

Bildschirmfoto 2021-08-14 um 20 42 56


But I already forked and fixed it there. I will point to that I18Next version and create a PR in I18Next :)

I will also test this again on every platform.

**Comment by Ahmadre** [comment]
@aguilaair All changes are uploaded to this PR. Could you please test this also on your side?

**Comment by aguilaair** [comment]
Works perfectly! Thank you @Ahmadre

**Comment by aguilaair** [comment]
@all-contributors please add @Ahmadre for bug

**Pull request merged**
