### PR TITLE
Improvements for windows

### PR DESCRIPTION
**Pull request by aguilaair**
- [x]  Fix issue where command-line process would stay alive after exiting the app in certain cases
- [x]  Fix issue where app title would be lowercase ("sidekick" instead of "Sidekick")
- [x]  Fix issue where the default icon would appear when hovering over the app instead of the sidekick logo
- [x]  Fix not being able to move or close the app when there is a DB error screen
- [x] Improve winUI appearance to fit more windows apps
- [x] Add mica effect to windows 11
- [ ] Support automated release to MS Store
- [x] Disable Automatic updates on MS Store version
image

### CODE REVIEW

**Comment by leoafarias** [comment]
@aguilaair the fix I just made seems it was a previous regression for some fixes. It seems that the button to maximize and so on have disappeared on the mac
CleanShot 2022-01-22 at 13 54 27@2x

**Comment by aguilaair** [comment]
Okay so we have two options here.

We can either add the window control buttons to the sidekick UI or we can just not set the window as frameless on macos

What do you prefer?

**Comment by aguilaair** [comment]
Should be fixed now @leoafarias

**Review by leoafarias — APPROVED** [review]
LGTM

**Pull request merged**
