### PR TITLE
Add app settings

### PR DESCRIPTION
**Pull request by aguilaair**
This PR implements application settings, right now the only two things that are loaded are the theme and the app version. However, in later updates they will allow the user to customize the application further, including:

- Open in IDE
- Custom GitHub Token

(these are coded already and can be enabled when needed) and others.

### CODE REVIEW

**Comment by aguilaair** [comment]
image

**Comment by leoafarias** [comment]
@aguilaair hold on this. I deprecated some things on FVM and have setup give already for some project settings.

As soon as I merge it should be easy to add the screen and dark mode.

**Comment by aguilaair** [comment]
Ok!

**Comment by leoafarias** [comment]
I have merged the settings service

**Pull request closed without merging**
