### PR TITLE
Fix CircularProgressIndicator never shown on first load

### PR DESCRIPTION
**Pull request by federicoviceconti**
I added on the AppReleasesState class the variable "isVersionReleaseFetchFinished", which is changed when the fetch of the Flutter version is done.

### CODE REVIEW

**Review by leoafarias — CHANGES_REQUESTED** [review]
@federicoviceconti thank for the PR, could you change `.isVersionReleaseFetchFinished` to `.loading` or `.fetching`, this will revert the flag but I think this will be better

**Comment by federicoviceconti** [comment]
Thanks for the feedback @leoafarias. I pushed the changed.

**Review by aguilaair — APPROVED** [review]
LGTM

**Review by leoafarias — APPROVED** [review]
I will make a small change to make the fetching a private property that cant be overridden by the constructor. But besides that will go ahead and do the merge

**Comment by leoafarias** [comment]
Thank you! @federicoviceconti

**Comment by aguilaair** [comment]
@all-contributors please add @federicoviceconti for bug

**Pull request merged**
