### PR TITLE
Feature/custom ide

### LINKED ISSUE #171: Open project with IntelliJ and Android Studio
First, I really love this project. Great work!😀 

I use `Android Studio` for all my flutter projects. It would be awesome if more IDEs than `VSCode` and `XCode` were supported.

### PR DESCRIPTION
**Pull request by aguilaair**
https://user-images.githubusercontent.com/29983481/151877362-01700615-0d50-4a72-aa41-e68ce237c37a.mp4

Closes #171

### CODE REVIEW

**Review by leoafarias — CHANGES_REQUESTED** [review]
It seems that the custom IDE feature does not work on the mac when testing against Android Studio.

**Comment by aguilaair** [comment]
@leoafarias what does it do?

**Comment by aguilaair** [comment]
@devj3ns what platform are you using (MacOS, Linux, or Windows)?

**Comment by devj3ns** [comment]
> @devj3ns what platform are you using (MacOS, Linux, or Windows)?

I am using windows

**Comment by aguilaair** [comment]
> I am using windows

Ok, it was just to see if you could try it if you had MacOS 😄

**Comment by aguilaair** [comment]
https://user-images.githubusercontent.com/29983481/153012067-1166c3e3-91e9-48d4-a4ee-fb0c261bbb18.mp4

In this perfectly legal video you can see it works fine when using the studio executable, @leoafarias.

**Comment by leoafarias** [comment]
> @leoafarias what does it do?
> 
> Edit: tested AS on WIndows, works fine
> 
> Edit2: Target the following file `/Applications/Android\ Studio.app/Contents/MacOS/studio`

Adjusting this path does work

**Comment by aguilaair** [comment]
> Adjusting this path does work


Hmmm, as you can see in the video, it works fine... Any ideas?

**Comment by aguilaair** [comment]
Ok, so is it ready to merge?

**Comment by rahat14** [comment]
Not Wrking on Macbook M1

**Comment by aguilaair** [comment]
Please open a new issue @rahat14 and provide some more details :)

**Pull request merged**
