### PR TITLE
Fix issue where onInstall would run even if version was intalled

### PR DESCRIPTION
**Pull request by aguilaair**
Fixes a bug whereby installation of a version starts even if the version is already installed

### CODE REVIEW

**Comment by leoafarias** [comment]
@aguilaair I don't think this is a proper fix. This button should only be displayed if the version is not installed. Not sure if you ran into this issue already, but most likely there should be a conditional to check when to render this, and not a conditional in the function

**Comment by aguilaair** [comment]
This is how it was previously, I caused this regression when fixing some overflows. However, i do agree this should be handled better.

**Comment by leoafarias** [comment]
I will review to see how it was before

**Comment by leoafarias** [comment]
No need for this. Thanks

**Pull request closed without merging**
